{% set name = "elfutils" %}
{% set version = "0.175" %}
{% set sha256 = "f7ef925541ee32c6d15ae5cb27da5f119e01a5ccdbe9fe57bf836730d7b7a65b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://fedorahosted.org/releases/e/l/elfutils/{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - m4

  run:
    - zlib

test:
  requires:
    - {{ compiler('c') }}

about:
  home: https://fedorahosted.org/elfutils/
  license: LGPL-3.0
  license_file: COPYING-LGPLV3
  summary: 'a set of utilities and libraries for handling ELF (Executable and Linkable Format) files.'

extra:
  recipe-maintainers:
    - edisongustavo
