{% set name = "elfutils" %}
{% set version = "0.173" %}
{% set sha256 = "b76d8c133f68dad46250f5c223482c8299d454a69430d9aa5c19123345a000ff" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://fedorahosted.org/releases/e/l/elfutils/{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - m4

  run:
    - zlib

about:
  home: https://fedorahosted.org/elfutils/
  license: LGPL-3.0
  summary: 'a set of utilities and libraries for handling ELF (Executable and Linkable Format) files.'

extra:
  recipe-maintainers:
    - edisongustavo
