{% set name = "elfutils" %}
{% set version = "0.194" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://fedorahosted.org/releases/e/l/{{ name }}/{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: 09e2ff033d39baa8b388a2d7fbc5390bfde99ae3b7c67c7daaf7433fbcf0f01e

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('elfutils', max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - make
  host:
    - m4
    - libmicrohttpd
    - bzip2 {{ bzip2 }}
    - libarchive {{ libarchive }}
    - libcurl {{ libcurl }}
    - sqlite {{ sqlite }}
    - xz {{ xz }}
    - zlib {{ zlib }}
    - zstd {{ zstd }}

test:
  requires:
    - {{ compiler('c') }}
    - pkg-config

about:
  home: https://fedorahosted.org/elfutils
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: COPYING-LGPLV3
  summary: a set of utilities and libraries for handling ELF (Executable and Linkable Format) files.
  description: a set of utilities and libraries for handling ELF (Executable and Linkable Format) files.
  home: https://sourceware.org/git/?p=elfutils.git;a=summary
  home: https://fedorahosted.org/elfutils

extra:
  recipe-maintainers:
    - edisongustavo
    - xhochy
