travis:
  secure:
    BINSTAR_TOKEN: Hw2AlxUw51ARaXyMfFDVQFDLIvLVcI/AljXrTOnX60jQw62d4C+BfP3nC1OXqaGeFY/Q+oVBQfsQwuj12zqt/5BE8/KyES4rNGvSjkQKWmmWGicWicuTNc19c/oKMUt+vLOmE2BCg9K+dWAXxMMLWLcYLzvgkobuvOuqO+YcprbSbuqhzN9q792LHDOP50qAcHHbaRMar1Mg696ontzkgaQFm1lVe+ZYFQ0J/slY1mEHu8BCpQAzCHXMDxpSQfkccpFSKEWeHclojjMNLhvuueaBuzdFe22MAjyzAOeM9/E9YNoXjvzYIIWnwO1PhXz61OYYwe6xIhGiNhWj2W60tE3pk+Xpa9U5aAkkYtnuhohmS3RffN8xkvgUJazg06ydH2Nk7AGSEV86TlGOmnVystQt6WaIhZDGlLp9Cukgr6fDLYGOkTuDevAncMvnKht5WNPLY1z1FyknKQtgbnbQ6jyd2Qz1prEMw/aW4f1O6bcGeR0NPWoIL0gEJQnBJlJR2ASFvovgO7Bpm0a6edmBd/JKWO9JBsj26o30ekvbSJIk45ZbYlNYbtIINaNgCq7qavd8dkBz1HX74kXgH4TW5QPd3t8NL2Ee89b7jry3m9ARLvgo9J9OnvsBamt1I5fmMDwBEpORixDnAqyhu+dXPrYDX3R6E6IpmR2NcZs22bs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
