travis:
  secure:
    BINSTAR_TOKEN: U+64ciBMm5uZzL/RzGMeg6KZlQ1OSX6N+DxmkGWjngzofc2C1ib0f0czImRArbseskBClOZw3mmx5UkZMmIc0P3LQTGySXC80iiaJXSI/F+w8k5jnq7M0lbvall4dfWuCdFMKP0cOgTGqy3iB3B5CcPOdOV+hU5DLI8KIQ5A8ugjfscIjh5TjNq6KLnW//kLruIwD7Noxs6T0ERU/TOsI00m2PAHwU6TaCKrL77U6IQ570t1M9bx5snVggynUM2rSPoUtDq7QzVRRUsp6hU7ITkw3yNLGA1lvvpHE7x9W/d8AFRxahA6OmWBhOJvxypgkhhUw+9FGuBe+o4ojGjaGT3c1F0eBytaXWQfuc6rDYQy9Lv9a+YmeGd7vOsLeXpGLfu3fI6mBy2zBr7HUFWeVmATBGVQqOVnxfLf27i0cAYojp92uRNEmFZWifu5WHmyyQMEdUNsVYaMfhx/PYhpcXcGT8NbGmiHAv0BHrQPuXUfphskVIZbyWQo3+z+hH3lk6MdCSkOTEsooLzs1iHV/eo8TtVUlSL1wvPCRCrrFKRbfAGbDkhuUsg8U2ah9UsKlt01CP4lWWKZqDZAK5jpRUnKudM54K+0ZDyYa04oWUzWwkN84w1bMsUOnJv3LR2Ixmw4F1u8UwNfVVttHmn70miMBEfofdVf/Me2BBiaFTQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
